services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        APP_ENV: development
    volumes:
      - ./src:/var/www/invoices_app
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - php
    volumes:
      - ./src:/var/www/invoices_app
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: invoices
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: wemJag4]5iS}5l0mIL}8
    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge