services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: true
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: invoices
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: wemJag4]5iS}5l0mIL}8
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge